name: Build

on:
  push:
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sdl-version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Get Latest Release Tag
        id: tag
        run: |
          SDL_TAG=$(curl --no-progress-meter --write-out "%{redirect_url}" https://github.com/libsdl-org/SDL/releases/latest | sed -E "s/.*\/releases\/tag\/([^#]*)#?.*/\1/")
          echo "tag=$SDL_TAG" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ${{ matrix.os }}
    needs: sdl-version
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gcc
            generator: Ninja
          - os: windows-latest
            compiler: cl
            generator: "Visual Studio 18 2026"
    defaults:
      run:
        shell: bash
    steps:
      - name: Install Linux dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: >
          sudo apt-get install build-essential git make
          pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev
          libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev
          libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev
          libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev
          libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libthai-dev libusb-1.0-0-dev
          libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev

      - name: Prepare for cloning
        run: mkdir clones

      - name: Get SDL
        working-directory: clones
        env:
          SDL_TAG: ${{ needs.sdl-version.outputs.tag }}
        run: git clone --depth 1 --branch $SDL_TAG https://github.com/libsdl-org/SDL.git

      - name: Configure SDL
        working-directory: clones/SDL
        run: >
          cmake -S . -B build -G "${{ matrix.generator }}"
          -DCMAKE_C_COMPILER=${{ matrix.compiler }}
          -DCMAKE_BUILD_TYPE=Release
          -DSDL_SHARED=ON
          -DSDL_STATIC=OFF
          -DSDL_TEST_LIBRARY=OFF
          -DSDL_TESTS=OFF
          -DSDL_DISABLE_INSTALL=ON
          -DSDL_DISABLE_INSTALL_DOCS=ON
          -DSDL_INSTALL_TESTS=OFF

      - name: Build SDL
        working-directory: clones/SDL
        run: |
          cmake --build build --config Release --parallel
          ls -la build

      - name: Upload built Dynamic Library file
        uses: actions/upload-artifact@v7
        with:
          path: clones/SDL/build/libSDL3.so
          archive: false

  push:
    runs-on: ubuntu-latest
    needs: [ sdl-version, build ]
    steps:
      - uses: actions/checkout@v7

      - name: Download built Dynamic Library files
        uses: actions/download-artifact@v8
        with:
          path: builds
        
      - name: Put Dynamic Library files into the correct spots
        run: |
          mkdir -p libs/SDL3/linux-x64
          cp builds/libSDL3.so libs/SDL3/linux-x64/
          git add libs

      - name: Setup git credentials for the GitHub Actions Bot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Mark success
        env:
          SDL_TAG: ${{ needs.sdl-version.outputs.tag }}
        run: |
          echo "$SDL_TAG" > libs/SDL3/version.txt
          git add libs/SDL3/version.txt

      - name: Push update
        run: |
          [[ $(git diff-index HEAD --) ]] || { echo "No updates found. No push necessary." >> $GITHUB_STEP_SUMMARY; exit 0; }
          git commit -m "Updated SDL"
          git pull --rebase
          git push
