name: Build

on:
  push:
    paths:
      - '.github/workflows'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: >
          sudo apt-get install build-essential git make
          pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev
          libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev
          libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev
          libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev
          libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libthai-dev libusb-1.0-0-dev
          libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev
          ninja-build

      - name: Prepare for cloning
        run: mkdir clones

      - name: Get SDL
        working-directory: clones
        run: |
          SDL_TAG=$(curl --no-progress-meter --write-out "%{redirect_url}" https://github.com/libsdl-org/SDL/releases/latest | sed -E "s/.*\/releases\/tag\/([^#]*)#?.*/\1/")
          git clone --depth 1 --branch $SDL_TAG https://github.com/libsdl-org/SDL.git

      - name: Configure SDL
        working-directory: clones/SDL
        run: >
          cmake -S . -B build -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DSDL_SHARED=ON
          -DSDL_STATIC=OFF
          -DSDL_TEST_LIBRARY=OFF
          -DSDL_TESTS=OFF
          -DSDL_DISABLE_INSTALL=ON
          -DSDL_DISABLE_INSTALL_DOCS=ON
          -DSDL_INSTALL_TESTS=OFF

      - name: Build SDL
        working-directory: clones/SDL
        run: >
          cmake --build build --config Release --parallel

      - name: Extract Dynamic Library files from build
        run: |
          mkdir -p runtimes
          cp clones/SDL/build/*.so* runtimes/ --no-dereference
          git add runtimes

      - name: Setup git credentials for the GitHub Actions Bot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Mark success
        run: |
          git -C clones/SDL describe --tags --exact-match > version_SDL
          git add version_SDL

      - name: Push update
        run: |
          git commit -m "Updated SDL"
          git push
